M48
; DRILL file {KiCad 7.0.6} date Mon Jul 31 04:45:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-31T04:45:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X7.9994Y-3.5282
X7.9994Y-3.7558
T2
X8.871Y-1.8
X8.8727Y-2.183
X8.8727Y-2.5714
X8.8727Y-2.9622
T0
M30
